### ISSUE TITLE
Does not work when updating the schema

### ISSUE THREAD

**Issue by codepunkt** [prisma-labs/vscode-graphql#104]
Syntax highlighting for queries/mutations in .gql files works fine. However, updating the schema that is pointed at from .graphqlconfig.yml does not change the autocompleted values, doesnt show errors on now non-matching queries and also doesn't update tooltips for changed comments on types.

Is this the expected behavior? Shouldn't this work?

**Comment by codepunkt** [comment]
Also, what do i need watchman for in the underlying `graphql-language-server` if it doesn't?

**Comment by blocka** [comment]
I'm looking for a better way for this too: In the meantime I kill all the prisma processes which restarts everything: `ps aux | grep prisma | awk '{print $2}' | xargs kill`

**Comment by ganemone** [comment]
This is actually an issue with the underlying `graphql-language-server`. I submitted a fix here: https://github.com/graphql/graphiql/pull/928

**Comment by remorses** [comment]
Anyone got this working? I have to reload vscode to update the autocomplete values

**Comment by cantiero** [comment]
Hi @ganemone. Thanks for this extension, it's awesome! It looks like your pull request was merged into graphql-language-server: https://github.com/graphql/graphiql/pull/928. But vscode-graphql v0.2.14 is not picking up  changes in schema. Is there anything else affecting this? If doing it automatically is not trivial, maybe having an vs code command to refresh the cache could be a good enough solution. Beats restarting the editor for sure.

**Comment by acao** [comment]
@cantiero we upgraded to the latest language service *just* recently, so you'll find your fix in `0.3.1`! enjoy!

**Comment by johhansantana** [comment]
I have my schema on a different local server and would like for it to update when I make changes to the schema. Is there a way to manually telling the plugin to refetch the schema?

**Comment by acao** [comment]
can you open a feature request? that is doable as a less than desirable workaround

hopefully someday soon we can show some docs on how to write a custom schema loader for graphql-config. @kamilkisiela may be able to help with that
