### ISSUE TITLE
Getting NetworkHelper: operation: query

### ISSUE THREAD

**Issue by mattharder91** [prisma-labs/vscode-graphql#108]
## Actual Behavior

Hi when executing a query through the extension i am getting the error 

Error opening content and in the output terminal I get the error Getting NetworkHelper: operation: query

## Expected Behavior

Getting the result of the query or at least an explanation why the query failed

## Steps to Reproduce the Problem Or Description

1. Executing the query:

#import "./XFragment.gql"

```
query xs {
  xs {
    x {
      ...X
    }
    success
    message
  }
}
```

my Configuration:

```
{
  "projects": {
    "myproject": {
      "schemaPath": "schema.graphql",
      "extensions": {
        "endpoints": {
          "default": {
            "url": "http://localhost:3000/api",
            "Authorization": "Bearer mytoken"
          }
        }
      }
    }
  }
}
```

## Specifications

  - GraphQL for VSCode Extension Version: 0.1.7
  - VSCode Version: 1.33.1
  - OS Name: Linux
  - OS Version: Ubutntu 16.04

## Logs Of TS Server || GraphQL Language Service

NetworkHelper: operation: query

**Comment by divyenduz** [comment]
@mattharder91 You should get the GraphQL/network errors in the pane that is also supposed to show the result on success. Does that not happen in your case? 

For example, if I run a query against a server that is not running, I get this error: 

![image](https://user-images.githubusercontent.com/746482/60028716-21f2ba00-96a0-11e9-9455-be8166882c25.png)

**Comment by acao** [comment]
@mattharder91 I found a few edge cases where this had regressed, and was able to fully restore the error handling
