### ISSUE TITLE
Jump to enum value definition

### ISSUE THREAD

**Issue by marktani** [prisma-labs/vscode-graphql#12]
When you CMD+Click on an enum value, it should jump to its definition.

Example: https://github.com/graphcool/graphql-server-example
CMD+Click on `ENTIRE_CABIN` in https://github.com/prismagraphql/graphql-server-example/blob/master/prisma/seed.graphql should jump to its definition in https://github.com/prismagraphql/graphql-server-example/blob/master/src/generated/prisma.graphql

**Comment by divyenduz** [comment]
This is fixed in the latest version of the extension for a while. This was most likely fixed via https://github.com/prisma-labs/vscode-graphql/pull/117
