### ISSUE TITLE
Jump to query/mutation definition

### ISSUE THREAD

**Issue by marktani** [prisma-labs/vscode-graphql#13]
When you CMD+Click on a mutation, it should jump to its definition.

Example: https://github.com/graphcool/graphql-server-example

CMD+Click on `createExperience` in https://github.com/prismagraphql/graphql-server-example/blob/master/prisma/seed.graphql should jump to its definition in https://github.com/prismagraphql/graphql-server-example/blob/master/src/generated/prisma.graphql

**Comment by acao** [comment]
@marktani this feature is included now, enjoy!
