### ISSUE TITLE
`Execute Query` does not work if the fragment mentioned in the query is not defined below the query definition

### ISSUE THREAD

**Issue by ma-petrovic** [prisma-labs/vscode-graphql#133]
## Actual Behavior

Even though `Go to definition` works, this happens when attempting to `Execute Query` which uses a `fragment`

### First scenario

```gql
query users {
  users {
    ...CompleteUser
  }
}

```

Results in `Error: Network error: Response not successful: Received status code 400`

### Second scenario

```gql
fragment CompleteUser on User {
  id
  name
  lastname
}

query users {
  users {
    ...CompleteUser
  }
}

```

Results in a blank result with the following log

```
NetworkHelper: operation: undefined
NetworkHelper: endpoint: http://localhost:4000

```

### Third scenario

```gql
query users {
  users {
    ...CompleteUser
  }
}

fragment CompleteUser on User {
  id
  name
  lastname
}

```

Results in a successful response

```gql
{
  "data": {
    "users": [
      {
        "id": "4192cd57-6236-4f8c-a96e-58ff9d53170e",
        "name": "A",
        "lastname": "B"
      },
      {
        "id": "9e22679b-7208-4d21-a906-ad3578baf9bb",
        "name": "C",
        "lastname": "D"
      },
      {
        "id": "f4a920d7-ed1a-4590-8c49-34087c52492f",
        "name": "E",
        "lastname": "F"
      }
    ]
  }
}

```

## Expected Behavior

Query executes successfully and returns the according data

## Steps to Reproduce the Problem Or Description

- git clone https://github.com/mateja176/js-meetup.git
- `cd js-meetup`
- `npm install`
- `npm run start:api`
- go to `app/src/apollo/queries/index.graphql`, line 1, column 1
- click `Execute Query` above the following query

```gql
query users {
  users {
    ...CompleteUser
  }
}

# ...

```

## Specifications

  - GraphQL for VSCode Extension Version: Latest
  - VSCode Version: 1.38.1
  - OS Name: Ubuntu, Linux
  - OS Version: 19.04

## Logs Of TS Server || GraphQL Language Service

```
NetworkHelper: operation: query
NetworkHelper: endpoint: http://localhost:4000

```

**Comment by ma-petrovic** [comment]
Additionally, adding a second `fragment` below causes the same error, i.e.:

```
query users {
  users {
    ...CompleteUser
  }
}

# ...

fragment CompleteUser on User {
  id
  name
  lastname
}

fragment NjamBase on Njam {
  id
  location
  time
  ordered
}

```

**Comment by acao** [comment]
@ma-petrovic if this is still an issue in 0.3.1, can you open a ticket in `graphql/graphiql` repo? thank you!
