### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by myeonghuSong** [prisma-labs/vscode-graphql#134]
- Issue Type: `Bug`
- Extension Name: `vscode-graphql`
- Extension Version: `0.2.2`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by info-house-by** [comment]
windows 10
Unable to open 'schema.graphql': Unable to read file '\\d:\\app\schema.graphql' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\app\schema.graphql').

**Comment by acao** [comment]
not clear what the original issue is here exactly!

@info-house-by, if you are still having issues with windows paths in the latest 0.3.1 extension release, can you open a new ticket?
