### ISSUE TITLE
Document symbols support

### ISSUE THREAD

**Issue by felixfbecker** [prisma-labs/vscode-graphql#135]
It would be amazing to have go to symbols support (Cmd+Shift+O). We have a big schema file and it is difficult to find types you are looking for with text search, because that matches both references and definitions, and also inside comments.

**Comment by acao** [comment]
@felixfbecker the LSP now supports this and we just updated! 0.3.1 generates the schema file for definition lookups by default, but 0.3.2 will allow you to override this if you us .graphql files to define schema ins source.
