### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by kingluddite** [prisma-labs/vscode-graphql#141]
- Issue Type: `Bug`
- Extension Name: `vscode-graphql`
- Extension Version: `0.2.2`
- OS Version: `Darwin x64 19.0.0`
- VSCode version: `1.40.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by kingluddite** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 29371,
		"activateCallTime": 12,
		"activateResolvedTime": 1,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "Prisma.vscode-graphql",
				"_lower": "prisma.vscode-graphql"
			},
			"activationEvent": "workspaceContainsTimeout:**/.graphqlconfig,**/.graphqlconfig.yml,**/.graphqlconfig.yaml"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Request initialize failed with message: \".graphqlconfig\" file is not available in the provided config directory: /Users/philiphowley/Documents/dev/ucla/online/catchup/catchup-lessons/jquery-api-ajax/catchup-session\nPlease check the config directory."
		}
	]
}
```

**Comment by divyenduz** [comment]
Request initialize failed with message: \".graphqlconfig\" file is not available. Do you have a graphql-config file in your project? If yes, please comment here. 

The extension only works with a valid `graphql-config` (2.x) file.

**Comment by acao** [comment]
@kingluddite if you're still having this issue, see the updated usage instructions here!

https://github.com/prisma-labs/vscode-graphql#usage
