### ISSUE TITLE
Update graphql-config to support '.graphqlrc' files

### ISSUE THREAD

**Issue by kripod** [prisma-labs/vscode-graphql#142]
While using [GraphQL Code Generator](https://graphql-code-generator.com/), I wanted to use a shared configuration for all GraphQL-related settings. While this project supports only the '.graphqlconfig' files as defined by `graphql-config@2`, graphql-codegen is on the edge with [`graphql-config@3`](https://graphql-config.com/docs/introduction), supporting only `.graphqlrc` files.

**Comment by aspirisen** [comment]
I don't know if it is possible now, but it would be good if you could select path to the config file in vscode settings

**Comment by acao** [comment]
we now support all graphql-config@3 filenames by default!
