### ISSUE TITLE
Cannot run execute query when adding a fragment to gql tags

### ISSUE THREAD

**Issue by hmoule** [prisma-labs/vscode-graphql#143]
## Actual Behavior
No execute query option
```
export const EXAMPLE_QUERY = gql`
   query exampleQuery {
      ID
      User {
         ...Fragment
     }
   }
 ${fragment}
`;
```

## Expected Behavior

Execute query option with graphql tags
```
export const EXAMPLE_QUERY = gql`
   Execute query <-----------
   query exampleQuery {
      id
      user {
         ...fragment
     }
   }
 ${fragment}
`;
```

## Specifications

  - GraphQL for VSCode Extension Version: 0.2.2
  - VSCode Version: 1.40.1
  - OS Name: macOS Catalina
  - OS Version:  10.15.1

**Comment by acao** [comment]
these features will not work with template tag replacement. there is no graphql parser that will support this, sadly!

maybe in a later version when we have a way to parse graphql this way. apollo's extension has the same issue

**Comment by jaydenseric** [comment]
This issue has been closed prematurely.

Although it makes sense you can't execute the query when the template string is using interpolation, surely the extension could detect that situation and not display an inline "Execute query" button that has broken functionality.

GraphQL queries in template strings with interpolation is a common, perfectly valid pattern - especially for including fragments like @hmoule displayed in his examples.
