### ISSUE TITLE
Syntax error: cannot parse the unexpected character "&"

### ISSUE THREAD

**Issue by vatosarmat** [prisma-labs/vscode-graphql#148]
## Actual Behavior
Error popup appears. "Go to definition" doesn't work. No GraphQL 14 support yet?
![Screenshot from 2020-03-07 18-18-45](https://user-images.githubusercontent.com/35213999/76141283-73b46680-60ae-11ea-92fc-1e0ee5fa95e5.png)

## Expected Behavior
No errors, "Go to definition" works

## Steps to Reproduce the Problem Or Description
Make new folder, place [github public schema](https://developer.github.com/v4/public_schema/) and .graphqlconfig with only "schemaPath" in it

## Specifications

  - GraphQL for VSCode Extension Version: 0.2.2
  - VSCode Version: 1.42.1
  - OS Name: GNU/Linux
  - OS Version: Ubuntu 18.04

## Logs Of TS Server || GraphQL Language Service
Syntax Error: Cannot parse the unexpected character "&".

**Comment by takumiya081** [comment]
face same problem.
crash suggestions

**Comment by matt-senseye** [comment]
Same here, and I seem to get no autocompletion at all in .graphql files

**Comment by acao** [comment]
![image](https://user-images.githubusercontent.com/1368727/92276495-119eb780-eebf-11ea-82db-1c381735699c.png)

works now in 0.3.1

if folks have any further issues with properly validating/completing with the relatively new "interfaces extending interfaces" feature, feel free to open a new ticket. enjoy!
