### ISSUE TITLE
Extension not associated with `.graphqls` files

### ISSUE THREAD

**Issue by cailloumajor** [prisma-labs/vscode-graphql#176]
## Actual Behavior
While this extension supports `.graphqls` files, Visual Studio Code is not aware of it.

## Expected Behavior
Associate this extension with `.graphqls` files.

## Steps to Reproduce the Problem Or Description
Open a `.grapphqls` file:
- without this extension installed, it is not recommended at all by Visual Studio Code
- with this extension installed, the file is not associated nor handled by the extension

## Specifications

  - GraphQL for VSCode Extension Version: 0.2.14
  - VSCode Version: 1.44.2
  - OS Name: Debian GNU/Linux
  - OS Version: bullseye/testing

## Logs Of TS Server || GraphQL Language Service
Not relevant

**Comment by cailloumajor** [comment]
See also:
- https://github.com/dncrews/GraphQL-SublimeText3/commit/a4c499efc8fbff80ecde49910ee4912dd6ac078a
- https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/master/CHANGELOG.md#140---2016-08-28

**Comment by acao** [comment]
i’m not in disagrement at all! just haven’t noticed it before. i will be sure to add it to the underlying LSP server repo, which is in graphql/graphiql. most of the business logic for this extension lives there

**Comment by cailloumajor** [comment]
> i’m not in disagrement at all!

Sorry, I felt you were by closing the issue...

**Comment by acao** [comment]
ope i guess i did. will get to all this soon!

**Comment by acao** [comment]
if you can, re-create this ticket for the language server? and you can add this extension to the list in a PR. they are all defined in one place

**Comment by cailloumajor** [comment]
@acao thank you for re-opening.

I think the problem is simpler than you think: the contents of `.graphqls` files is standard GraphQL language, the extension is just different to denote the purpose of the file, i.e. schema definition. My request here is just that VSCode handles `.graphqls` files exactly the same manner as `.graphql` files. There is no need to add a new language.

My apologies if my request was not clear enough.

I achieved to obtain the needed behavior by adding `".graphqls"` to the array below in `package.json`.
https://github.com/prisma-labs/vscode-graphql/blob/6bdfa89e63f737134b2d9a6a4e8959092b0e2fbf/package.json#L48-L51

If you agree with this change, I would be glad to open a pull request.

**Comment by acao** [comment]
please open the PR, you don’t need my permission!
you will also need a PR to `graphql/graphiql` repo, otherwise you’ll only have highlighting support for `.graphqls` files

**Comment by acao** [comment]
for reference, [this line](https://github.com/graphql/graphiql/blob/6114f2af3cc645677e6ebc8438dbec05d7ff1705/packages/graphql-language-service-server/src/findGraphQLTags.ts#L36) would be the only other thing you need to change for this to work end to end!
