### ISSUE TITLE
Multiple interface implementation "&" marked as error

### ISSUE THREAD

**Issue by everdrone** [prisma-labs/vscode-graphql#18]
![screenshot](https://user-images.githubusercontent.com/22671061/41465791-e0ac50d2-709f-11e8-889c-0ad8f838022e.png)

The `&` symbol is used to implement multiple `interface`s into a `type`

[source](http://facebook.github.io/graphql/draft/#example-ab5e5)

**Comment by divyenduz** [comment]
@everdrone : Thanks for pointing this out. I understand that this is a feature from the draft spec that will be released with graphql-js `14.x`.

The [`graphql-language-service`](https://github.com/graphql/graphql-language-service) still relies on graphql-js `12.x` and this will be fixed once we are able to port the language service to use `14.x`. 

I will see if I can pick this up sometime soon. Thanks!

**Comment by everdrone** [comment]
I see, didn’t know this was related to the language service
I’ll keep an eye on that issue too

**Comment by divyenduz** [comment]
Created an issue https://github.com/graphql/graphql-language-service/issues/244 to track the progress of this.

**Comment by divyenduz** [comment]
This was fixed upstream and should be available in extension version `0.2.0`. Please re-open a new issue/comment here if the issue persists.

**Comment by zolotokrylin** [comment]
dear maintainers, I still have the issue 
![image](https://user-images.githubusercontent.com/1125014/90595566-bbbfe380-e21f-11ea-915d-d62b794b2bc9.png)

extension version 

![image](https://user-images.githubusercontent.com/1125014/90595587-c7130f00-e21f-11ea-8e5c-a9d3f86d40c1.png)

How to fix it? Thanks!

**Comment by acao** [comment]
0.3.1 released! please open new tickets if you have any issues
