### ISSUE TITLE
Add option to hide "execute mutation" in code

### ISSUE THREAD

**Issue by homoky** [prisma-labs/vscode-graphql#189]
## Actual Behavior

No config for setting if `execute` will be shown in query on mutation.

## Expected Behavior

Boolean config where it can be hidden with.

## Specifications

  - GraphQL for VSCode Extension Version: 0.3 Insider
  - VSCode Version: GraphQL Insiders
  - OS Name: Mac OS X
  - OS Version: Big Sur

**Comment by acao** [comment]
this is relatively easy because it's entirely client side, and our current major blockage is loading settings on the language server side

**Comment by acao** [comment]
this was added in 0.3.0!

**Comment by tetchel** [comment]
For anyone else looking for this, the setting is  ` "vscode-graphql.showExecCodelens": false`

**Comment by acao** [comment]
Yep! The readme explains all of the vscode and graphql config extension settings
