### ISSUE TITLE
Support VSCode's indentation setting

### ISSUE THREAD

**Issue by JVimes** [prisma-labs/vscode-graphql#200]
## Actual Behavior

With the extension installed, the "Format Document" command indents with tabs even when VSCode is configured to use spaces.

## Expected Behavior

The "Format Document" command follows the VSCode setting on tabs vs spaces, and number of spaces:

![image](https://user-images.githubusercontent.com/6148201/90426488-61d3e800-e07e-11ea-839f-034d5f1ae2a6.png)

## Steps to Reproduce the Problem Or Description

1. Open a document in GraphQL language mode
2. Run the "Format Document" command.

## Specifications

  - GraphQL for VSCode Extension Version: v0.2.35
  - VSCode Version: 1.49.0-insider
  - OS Name: Windows 10
  - OS Version: Version 1903 (OS Build 18362.1016)

**Comment by acao** [comment]
thanks for reporting! this is a much less than ideal bug.

so, this extension does not implement code formatting. so you might have better luck over at the [`prettier-vscode` repository](https://github.com/prettier/prettier-vscode). it could be an issue in their implementation, or an issue with the actual `@prettier/parser-graphql` or whaever it's called. We use that in our official monaco mode, but not in the language server or in this extension. hope this helps!

**Comment by JVimes** [comment]
Oh, thank you. I'll report to prettier-vscode.
