### ISSUE TITLE
Error: Request textDocument/documentSymbol failed with message: A cached document cannot be found.

### ISSUE THREAD

**Issue by hendrikbursian** [prisma-labs/vscode-graphql#210]
## Actual Behavior

The Output panel is popping up on saving and editing typescript files in short intervals.

The following message is shown:

```
[Error - 19:29:28] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: A cached document cannot be found.
  Code: -32603
```

What follows are my settings. I also tried it with different configuration formats and settings.

`Extension Settings`
```json
  "vscode-graphql.debug": true,
  "vscode-graphql.trace.server": "on",
  "vscode-graphql.config.baseDir": "./",
  "vscode-graphql.config.filePath": ".graphqlrc",
```

## Expected Behavior

I can edit and save files without errors of the `vscode-graphql` extension.

## Steps to Reproduce the Problem Or Description
1. Open ts file
1. Making inputs - Adding newlines, typing, saving

## Specifications

  - GraphQL for VSCode Extension Version: `graphql.graphql-vscode-insiders` `0.3.5`
  - VSCode Version: 
    ```
    Version: 1.49.0-insider
    Commit: 8c9b4015feb0297d99c8051c35e85d208ffe83e3
    Date: 2020-09-03T07:13:55.843Z
    Electron: 9.2.1
    Chrome: 83.0.4103.122
    Node.js: 12.14.1
    V8: 8.3.110.13-electron.0
    OS: Linux x64 5.4.0-45-lowlatency snap
    ```
  - OS Name: `Ubuntu`
  - OS Version: `20.04.1 LTS`

## Logs Of TS Server || GraphQL Language Service
`TS Server Logs` don't show anything when the error occurs.
```
[Info  - 17:36:59.425] Starting TS Server 
[Info  - 17:36:59.425] Using tsserver from: /snap/code-insiders/516/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 17:36:59.426] <syntax> Forking...
[Info  - 17:36:59.443] <syntax> Starting...
[Info  - 17:36:59.444] <semantic> Forking...
[Info  - 17:36:59.456] <semantic> Starting..
```

`GraphQL Language Service` is repeating the following (paths obscured). The more I type the more frequently.
```
03/09/2020, 19:46:50 [4] (pid: 753955) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didChange","projectName":"default","fileName":"file:///path/to/edited-file.ts"}

[Error - 19:46:50] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: A cached document cannot be found.
  Code: -32603 
03/09/2020, 19:46:51 [4] (pid: 753955) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"default","fileName":"file:///path/to/edited-file.ts"}

03/09/2020, 19:46:51 [4] (pid: 753955) graphql-language-service-usage-logs: {"type":"usage","messageType":"workspace/didChangeWatchedFiles","projectName":"default","fileName":"file:///path/to/edited-file.ts"
```

I'd be happy to share more information as I really appreciate your work on this extension. It simply works as expected without hassle for me. I don't see that in the other GraphQL extensions.

**Comment by acao** [comment]
are you using `prisma.vscode-graphql@0.3.1`?

**Comment by hendrikbursian** [comment]
Hey, no its `0.3.5`

**Comment by acao** [comment]
ah, then you have the “insiders edition” installed. make sure to uninstall that one (`graphql.vscode-graphql-insiders`) and install `prisma.vscode-graphql`, the stable extension

**Comment by hendrikbursian** [comment]
Yes, I have tried with the other version before but had no luck.

I followed your advice and it works now. It seems I tricked myself with changed  configurations.

Thank you for the fast response. Have a good evening and keep up the good work! :)

**Comment by djsmedes** [comment]
I am now having this issue. It's on the latest version of this extension (v0.3.10, here https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql). I've tried every combination of uninstalling/reinstalling, clearing caches, switching to the insiders edition, switching back, and restarting my whole machine, and it's still happening.

@acao why did you ask about the insider's edition? Do you have a specific hypothesis about what's happening with some other kind of troubleshooting I could attempt?

**Comment by acao** [comment]
so, the output panel is still appearing?

**Comment by acao** [comment]
did you try closing the output panel? the error is normal to see as the cache is being built, but the configuration was added to the extension and this bug should not be visible in the latest version

**Comment by djsmedes** [comment]
The output panel is not the problem - it's not even opening automatically, I had to go and find it. My real problem is that the autocomplete and jump-to-definition parts of this extension are just completely non-functional. I assumed that since I was seeing an error in the log it was related. But if this error is part of normal expected operation, I guess I'll need to take another look at what's happening on my machine and possibly open a separate issue.

Thanks for your fast reply!

**Comment by acao** [comment]
sounds like a configuration issue with your graphql config. can you open a support ticket?

**Comment by djsmedes** [comment]
Sure, that would be helpful! Is that just another GitHub issue?
