### ISSUE TITLE
Changelog is missing

### ISSUE THREAD

**Issue by iddan** [prisma-labs/vscode-graphql#219]
The VSCode extension lacks a changelog

**Comment by acao** [comment]
this pinned issue is the best summary of recent changes so far
https://github.com/prisma-labs/vscode-graphql/issues/181

most of the changes have been made and automatically documented here and in other underlying dependencies:
https://github.com/graphql/graphiql/blob/main/packages/graphql-language-service-server/CHANGELOG.md

i currently don't have time to manage changelogs in duplicate, as most of the relevant changes are to the underlying language server which is used by many extensions. that said, i do plan on improving how changes are documented, possibly by switching to a different release management tool than lerna publish/conventional changelogs.

also, expect a blog post to summarize the new features soon!

**Comment by iddan** [comment]
Cool, currently it looks a little in VSCode. Maybe better change the markdown file to include a link to the actual changelog

**Comment by acao** [comment]
added a changelog! not as cross referential as I’d like, but a quick summary at least. my blog post will cover more depth on new features!
