### ISSUE TITLE
Cannot go to definition of type used in fragment

### ISSUE THREAD

**Issue by marktani** [prisma-labs/vscode-graphql#38]
In `queries/queries.graphql`.
```
fragment ExperienceFragment on Experience {
  id
  title
  category {
    mainColor
    name
  }
  slug
  numRatings
  avgRating
  pricePerPerson
}
```

CMD+Click on `Experience` should go to `Experience` definition in `src/schema.graphql`.

https://github.com/prismagraphql/graphql-server-example

**Comment by divyenduz** [comment]
This works as soon as I change `schema.graphql` and it is re-read by language service. Most likely, this is a bug with reading relevant graphql files.

**Comment by acao** [comment]
confirmed this is working for me. make sure that you include these files using the `documents` field in graphql-config@3, formerly known as `include`
