### ISSUE TITLE
enhancement: filter out invalid, built-in intellisense/emmet suggestions in (ts/js)x

### ISSUE THREAD

**Issue by sorenbs** [prisma-labs/vscode-graphql#4]
Bringing up auto-complete using ctrl-space shows too many suggestions:

![image](https://user-images.githubusercontent.com/281337/41218561-da166a56-6d5b-11e8-9bba-4dfb6968b8ae.png)

Writing the first letter is better:

![image](https://user-images.githubusercontent.com/281337/41218578-e63f27c8-6d5b-11e8-9661-eaff3c92aeda.png)

Picking `inp` will autocomplete like this:

![image](https://user-images.githubusercontent.com/281337/41218807-9dcd4730-6d5c-11e8-8473-f492cf862c84.png)

Can we fix ctrl-space?

**Comment by peterschussheim** [comment]
I agree with @sorenbs, snippets should be a separate extension or add a setting to disable.

**Comment by divyenduz** [comment]
Related: https://github.com/Microsoft/vscode/issues/45039

**Comment by acao** [comment]
oh great! so glad to find this. the vscode developers slack had written this off as impossible last month, and it has been bothering me to no end 😆 

this will definately be in `0.3.2`

**Comment by acao** [comment]
I've updated the README with instructions on how to configure this for yourself, as we don't have a way to programatically set this setting for users

https://github.com/prisma-labs/vscode-graphql#in-jsx-and-tsx-files-i-see-completion-items-i-dont-need

you may have to disable a few other types beyond just snippets. if you still have issues after this, please open another ticket!
