### ISSUE TITLE
Jump-to-definition not working within schema definition file

### ISSUE THREAD

**Issue by AndrewIngram** [prisma-labs/vscode-graphql#43]
I'm using Relay, so our project only has a single `.graphql` file, which is the schema itself. I'd expect to be able to cmd-click on things (or use jump to definition menu item) to jump around the file itself, but VSCode is telling me there's no definition found.

This is my `.graphqlconfig` file:

```json
{
  "schemaPath": "data/schema.graphql",
  "includes": ["**/*.graphql"]
}
```

Log output from GraphQL Language Server:

```
ZEBRA 1: undefined undefined
ZEBRA: GraphQLProjectConfig {
  config: 
   { schemaPath: 'data/schema.graphql',
     includes: [ '**/*.graphql' ] },
  configPath: '/Users/andrewingram/Repositories/tego-app/.graphqlconfig',
  projectName: undefined } /Users/andrewingram/Repositories/tego-app/data/schema.graphql
```

**Comment by divyenduz** [comment]
@AndrewIngram : Thanks for raising the issue. Can you please provide a minimal reproduction (or the single graphql file) as a github gist/repo? Will expedite things at my end. 

I will look into it tomorrow evening or over the weekend. Thanks.

**Comment by divyenduz** [comment]
@AndrewIngram : Also, Generally, one file schema jump should work without the includes. But what are you trying to jump on? We currently support it for Enum, types and input types only. Not scalars etc.

**Comment by AndrewIngram** [comment]
Here's the simplest repro I can make (I grabbed the schema from the graphql-js project codebase) https://github.com/AndrewIngram/vscode-graphql-repro

I'm not seeing any jump-to-definition behaviour on anything.

**Comment by divyenduz** [comment]
Thanks! I will look into it asap and revert. I have to test it with `.graphqlconfig` - JSON but in the meantime, would it be possible to use the `yml` format and rename config to `.graphqlconfig.yml`.

That might work. Thanks.

**Comment by AndrewIngram** [comment]
Type:

![image](https://user-images.githubusercontent.com/35227/42043317-0ff24b78-7aee-11e8-8df2-3ed4e33154ee.png)

Enum:

![image](https://user-images.githubusercontent.com/35227/42043349-24e89f00-7aee-11e8-8123-b7c62b71ec11.png)

**Comment by AndrewIngram** [comment]
I've changed the repro to use yaml, but it hasn't made any difference

**Comment by divyenduz** [comment]
@AndrewIngram : Thanks, I will look into this soon and revert :)

**Comment by divyenduz** [comment]
Created an issue https://github.com/graphql/graphql-language-service/issues/244 to track the progress of this.

**Comment by acao** [comment]
@AndrewIngram check out 0.3.1! I still need to expose the option to use .graphql files as source for 0.3.2 (by default generates from `projectConfig.getSchema()` result), but at least you'll have jump to definition!
