### ISSUE TITLE
Automate releases and CI/CD setup

### ISSUE THREAD

**Issue by divyenduz** [prisma-labs/vscode-graphql#45]
- Automate publishing of extension
- CI/CD with test cases
- Bots to automate the Github issues/PR workflow (maybe?)

**Comment by thakkaryash94** [comment]
Hey @divyenduz , I would like to work on this issue.

**Comment by divyenduz** [comment]
@thakkaryash94 Thanks! can you please reach out to me in `prisma.slack.com`? My username is `divyenduz`
