### ISSUE TITLE
[Icon Request] Support for graphql files

### ISSUE THREAD

**Issue by karloluis** [prisma-labs/vscode-graphql#56]
Current state
![screen shot 2018-07-27 at 11 47 00 am](https://user-images.githubusercontent.com/4258614/43331030-d3118bc2-9192-11e8-8ce1-64b961bf91af.png)

Description:

Add missed ".graphql" and ".gql" extensions for files to support graphql icon. many people reported this issue on vscode-icons and they referred developers to submit the request directly to the extensions.

Checklist:

 I'm sure this issue is not a duplicate?
Thanks.

**Comment by johannpinson** [comment]
Hello @karloluis 

I'm not sure it's the goal of this extension.
Instead, I recommand you the [`vscode-icons`](https://github.com/vscode-icons/vscode-icons) extension, it works well with `.graphql` and `.gql` files 😉

**Comment by jsjoeio** [comment]
I've never worked on a .vscode extension but looking at the [VSCode docs](https://code.visualstudio.com/api/extension-capabilities/theming#adding-a-new-icon-theme), it can't be that difficult, right? 

Any thoughts on the amount of effort required @johannpinson ?

**Comment by johannpinson** [comment]
Hey @jsjoeio 
It looks like simple, I will try to do it this weekend or asap.

**Comment by jsjoeio** [comment]
@johannpinson you rock! 🙌🏼 Thank you! I think it'll greatly improve the UX of this extension. Happy to test or help if needed!

**Comment by acao** [comment]
looks like vscode has included this icon themselves because they like us so much! i don't have any supplemental extensions for icons installed, and i see it there now. maybe it's my theme? can anyone else confirm?

**Comment by karloluis** [comment]
Closing since this is no longer an issue
