### ISSUE TITLE
How to install Watchman on windows!

### ISSUE THREAD

**Issue by guledali** [prisma-labs/vscode-graphql#62]
I have installed the plugin, reload the application and then headed over to my `schema.graphql`

**So this is what thus plugin should do!**

1. syntax highlighting (type, query, mutation, interface, union, enum, scalar, fragments)
2. autocomplete suggestions
3. validation against schema
4. snippets (interface, type, input, enum, union)
5. hover support
6. go to definition support (input, enum, type)

It does none of those things for me
I'm also getting this error
![watchman](https://user-images.githubusercontent.com/20647282/44617199-01c75400-a85f-11e8-9db2-7aa0552bd0d5.png)

Question how do I install Watchman on my windows machine, I looked at facebook guide and it's little bit advanced.

**Comment by vadistic** [comment]
I think you mixed up GraphQL extensions. I think you are trying to use [this one](https://github.com/kumarharsh/graphql-for-vscode). AFAIK vscode-graphql by Prisma does not require watchman 😃 

(Btw. To install watchman - just download the zip, extract it somewhere - i.e to `C:\Users\USERNAME\AppData\Local\` & add to your `PATH`)

**Comment by guledali** [comment]
Installing watchman` C:\Users\USERNAME\AppData\Local\` & add to your `PATH`)

What do mean add to your PATH? I actually navigated to that `PATH` put the `watchman.exe `file their and it still didn't work.

**Comment by vadistic** [comment]
@guledali  I'm really sorry for late reply.

> What do mean add to your PATH?

I just meant that you need make sure watchman localisation is on PATH environmental variable for your system/ user

Straight from watchman docs: 
>Extract the zip file and make sure that watchman.exe is located in a directory that is in your PATH.

Quick instructions for imo the quickest way to do it:
1) So you put watchman directory in `C:\Users\USERNAME\AppData\Local\` (so `watchman.exe` is in `C:\Users\USERNAME\AppData\Local\watchman\watchman.exe`)
2) Open PowerShell as Administrator
3) Add directory to PATH env variable by using `setx path "%path%;C:\Users\USERNAME\AppData\Local\watchman"`
4) You can check that it was added: `$ENV:PATH`
5) And that watchman is found: `watchman -v`

Voilà!

**Comment by MIKI0N** [comment]
> Quick instructions for imo the quickest way to do it:
> 
>     1. So you put watchman directory in `C:\Users\USERNAME\AppData\Local\` (so `watchman.exe` is in `C:\Users\USERNAME\AppData\Local\watchman\watchman.exe`)
> 
>     2. Open PowerShell as Administrator
> 
>     3. Add directory to PATH env variable by using `setx path "%path%;C:\Users\USERNAME\AppData\Local\watchman"`
> 
>     4. You can check that it was added: `$ENV:PATH`
> 
>     5. And that watchman is found: `watchman -v`
> 
> 
> Voilà! 

@vadistic Your instructions worked, but also replaced all the custom directories that were in the User Path variable with the system Path directories. As a result, I started to have issues while installing or reinstalling node modules with npm (like when installing a module, it would finish successfully, but node couldn't find it later). 

I needed to restore my computer to a point before I did everything you said in order to fix the issue. 

I'm pretty sure it wasn't your intention, but be more careful with what you suggest to people. There's always going to be people that follow instructions or tutorials without first verifying what it truly does (as me, in this case).

**Comment by acao** [comment]
watchman is no longer required for the language server, and thus for this extension!

enjoy windows users! if you have any other issues with paths/etc, please open a new ticket!
