### ISSUE TITLE
Auth from outside .graphqlconfig

### ISSUE THREAD

**Issue by covertbert** [prisma-labs/vscode-graphql#68]
Our `.graphqlconfig` references API tokens that are set in this manner `"Authorization": "Bearer ${env:API_TOKEN}"` with `API_TOKEN` being a token that changes regularly and is set via `export API_TOKEN=` in a shell.

Is there any way we can get this extension to authenticate properly so we can use the "execute query/mutation" features etc? Currently, of course, it will just say "API_TOKEN is not set"

**Comment by divyenduz** [comment]
Thanks for raising this issue. I will need to reproduce this. Do you have a small project maybe that I can use to reproduce this?

**Comment by covertbert** [comment]
Unfortunately I don't have a project that I'm able to share, however replicating this should be as simple as the following:

* Create a project with a `.graphqlconfig` that contains something like this
```
{
  "projects": {
    "myProject": {
      "schemaPath": "schema.graphql",
      "extensions": {
        "endpoints": {
          "local": {
            "url": "http://localhost:8000/app_dev.php/graphql",
            "headers": {
              "Authorization": "Bearer ${env:API_TOKEN}"
            }
          }
        }
      }
    }
  }
}
```
* Set `API_TOKEN` via `export API_TOKEN=xxxx` in the command line.
* Have the prisma plugin read this variable

Apologies as I know this will still need quite a lot of set up on your part to replicate!

**Comment by acao** [comment]
@covertbert with the `graphql-config@3.0.0` upgrade, you'll be able to use commonjs files, so you'll be able to do:

```js
const { API_TOKEN } = process.env
module.exports = {
  projects: {
    myProject: {
      schema: "schema.graphql",
      extensions: {
        endpoints: {
          local: {
            url: "http://localhost:8000/app_dev.php/graphql",
            headers: {
              Authorization: `Bearer ${API_TOKEN}`
            }
          }
        }
      }
    }
  }
}
```

**Comment by acao** [comment]
`prisma.vscode-graphql@0.3.1` released! please open new tickets if you have any issues
