### ISSUE TITLE
Directive errors

### ISSUE THREAD

**Issue by jascodes** [prisma-labs/vscode-graphql#74]
![screenshot 8](https://user-images.githubusercontent.com/1231593/45926131-d2c6ff80-bf3c-11e8-8785-a9c3114ff721.png)

https://github.com/prisma/prisma/issues/3177

**Comment by pantharshit00** [comment]
getting not exact same but similar error

```
[GraphQL: Validation] Directive "pgTable" may not be used on OBJECT.
```

**Comment by hundsim** [comment]
Same here. Whenever I do any change to the `datamodel.prisma` file, I'm getting validation errors on the directives. 

![image](https://user-images.githubusercontent.com/1907343/50419531-88059e00-0831-11e9-9cb1-5c39b3c890c3.png)

This is shown on hover:
>> Unknown directive "unique".GraphQL: Validation

When I do a "Reload Window" they disapear.

**Comment by Rachomir** [comment]
Any idea how to fix it?

**Comment by cheepo2109** [comment]
Any updates?

**Comment by ZempTime** [comment]
I'm running into this now, as well.

**Comment by yauul** [comment]
Same issue here. Trying to find a solution.

**Comment by ZempTime** [comment]
To be clear, I'm not on a `.prisma` file - I'm pointed towards `datamodel.graphql`. I've been having to turn the extension off

**Comment by betodasilva** [comment]
@ZempTime thanks for the recommendation

**Comment by marcelo-umg** [comment]
It is incredible that this was open on 2018, it is 2020 and there are no answers from any one on this team.

**Comment by luettgau** [comment]
Thanks @ZempTime, 
I installed another GraphQL syntax extension and now I'm fine.

**Comment by nysamnang** [comment]
Add `includes` key to the `.graphqlconfig` and reload vscode solved my problem.


```
{
  "projects": {
    "myapp": {
      "schemaPath": "./src/schema.graphql",

      "includes": ["**/*.graphql"],

      "extensions": {
        "endpoints": {
          "default": "http://localhost:4466"
        }
      }
    }
  }
}
```

**Comment by acao** [comment]
in graphql-config 3.0 itll be `documents`, but yes this does it!
also note that in graphql 15, directive definitions for introspection JSON are enhanced

**Comment by acao** [comment]
ok folks, try `graphql.graphql-vscode-insiders` 0.3.5, if you can? it's a pre-release of this extension.  it should cache a temporary file with the entire output of `graphql-config.getSchema()`, which now should generate full definition declarations for lookup. you'll need to use graphql-config@3 which is slightly different than the above config. .prisma files might not be fully supported anymore. if you have any feedback, we are doing all of that in #184

**Comment by acao** [comment]
`prisma.vscode-graphql` 0.3.1 released! please open new tickets if you have any issues
