### ISSUE TITLE
Prisma directives

### ISSUE THREAD

**Issue by affanshahid** [prisma-labs/vscode-graphql#85]
The extension does not seem to be able to recognize the built in prisma directives: `@relation, @unique` etc in my `datamodel.prisma`. 

Do I need to do some configuration?

## Specifications

  - GraphQL for VSCode Extension Version:  0.1.5
  - VSCode Version: 1.28.2
  - OS Name: Windows
  - OS Version: 10

## Logs Of TS Server || GraphQL Language Service

GQL Language Service logs:
```
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
is in debug mode: false
is in debug mode: false
```

**Comment by grantpant** [comment]
Did you resolve this? I'm experiencing the same issue.

**Comment by LeonardoGentile** [comment]
I have the same problem.
In my case although I've installed watchman and it is running fine.

This is my schema 
![image](https://user-images.githubusercontent.com/412061/56677882-bb621780-66c1-11e9-9f04-278ba7c0ccce.png)

And this is the console log 
![image](https://user-images.githubusercontent.com/412061/56677843-a5545700-66c1-11e9-9d62-030a7cde5721.png)

**Comment by mssalnikov** [comment]
Still having this issue, which unfortunately makes this extension unusable with prisma. Quite ironic actually =)

**Comment by blorriman** [comment]
same issue

**Comment by Scapeuce** [comment]
me too!!

**Comment by acao** [comment]
sorry for these issues, but Prisma decided to drop support for `.prisma` files in our most recent release `0.3.1`

it would be possible for someone to fork this extension if they wanted to maintain legacy support themselves!
