### ISSUE TITLE
Add warning to readme that this plugin does not work

### ISSUE THREAD

**Issue by steida** [prisma-labs/vscode-graphql#94]
To save people time.

https://github.com/prisma/vscode-graphql/issues/93
https://github.com/prisma/vscode-graphql/issues/89
https://github.com/prisma/vscode-graphql/issues/88
https://github.com/prisma/vscode-graphql/issues/87

Thank you.

**Comment by steida** [comment]
Meanwhile, this extension works for me: https://github.com/kumarharsh/graphql-for-vscode

Just ` npm install @playlyfe/gql --dev` and then the extension itself.

A minimal example is great enough: https://github.com/kumarharsh/graphql-for-vscode#a-minimal-example

**Comment by steida** [comment]
But import somehow sucks, it imports everything and then warns about clashes.

**Comment by steida** [comment]
But import somehow sucks, it imports everything and then warns about clashes. Without importing from generated prisma schema, it works.

**Comment by 19majkel94** [comment]
@steida Does `kumarharsh/graphql-for-vscode` works for you with the newest `graphql-js` v14? 😕

**Comment by steida** [comment]
@19majkel94 It looks like it works.

**Comment by steida** [comment]
@19majkel94 Check https://github.com/este/este-typescript

**Comment by divyenduz** [comment]
@steida : Thanks for raising this. I will take a look at this soon, I already commented on the 4 issues you mentioned here asking for more information or suggesting resolutions. Thanks!

**Comment by 5achinJani** [comment]
#75

**Comment by acao** [comment]
all the issues noted have been fixed, or resolutions have been provided.

please open new tickets if you have issues with the latest versions! thanks!
